name: macOS 15
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  python_bindings_macos_15:
    uses: ./.github/workflows/python_bindings_reusable.yaml
    with:
      run_os: macos-15
