name: Windows 2022
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  python_bindings_windows_2022:
    uses: ./.github/workflows/python_bindings_reusable.yaml
    with:
      run_os: windows-2022
