name: Jazzy
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build_ros_jazzy:
    uses: ./.github/workflows/ros_build_reusable.yaml
    with:
      ros_distro: jazzy
      container_image: osrf/ros:jazzy-desktop
